name: CD - Deploy to Production

on:
  workflow_run:
    workflows: ["CI - App Build & Test"]
    types: [completed]
    branches: [main, develop]

jobs:
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: >
      ${{
        github.event.workflow_run.conclusion == 'success' &&
        github.event.workflow_run.event == 'push' &&
        (github.event.workflow_run.head_branch == 'main' ||
         github.event.workflow_run.head_branch == 'develop')
      }}

    steps:
      - name: Checkout code (same commit tested by CI)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Debug workflow information
        run: |
          echo "Workflow:  ${{ github.event.workflow_run.name }}"
          echo "Branch:    ${{ github.event.workflow_run.head_branch }}"
          echo "Event:     ${{ github.event.workflow_run.event }}"
          echo "SHA:       ${{ github.event.workflow_run.head_sha }}"
          echo "Conclusion:${{ github.event.workflow_run.conclusion }}"

      - name: Copy compose and configs to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USERNAME }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          source: |
            docker-compose.yml
            init.sql
          target: /opt/subscription-manager

      - name: Deploy to production server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USERNAME }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          script: |
            set -euo pipefail
            cd /opt/subscription-manager

            BRANCH="${{ github.event.workflow_run.head_branch }}"
            IMAGE="${{ secrets.DOCKER_USERNAME }}/subscription-manager:${BRANCH}"
            echo "Using image: ${IMAGE}"

            echo "Stopping running services (if any)..."
            docker compose ps -q | xargs -r docker stop

            echo "Pulling latest image..."
            docker pull "${IMAGE}"

            echo "Starting services..."
            docker compose up -d --build

            echo "Waiting for services..."
            sleep 20

            echo "Health check..."
            for i in $(seq 1 30); do
              if curl -f http://localhost:3000/health >/dev/null 2>&1; then
                echo "✅ Healthy"
                exit 0
              fi
              echo "Attempt $i/30..."
              sleep 5
            done

            echo "❌ Failed health check"
            docker compose ps
            docker compose logs app
            exit 1
